//ui actions
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';
export const ACTIVE_ADD_TASK = 'ACTIVE_ADD_TASK';
export const DEACTIVE_ADD_TASK = 'DEACTIVE_ADD_TASK';
export const TOOGLE_COMPLETE_TASK_SHOW = 'COMPLETE_TASK_SHOW';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
//my day task action

export const ON_TASK_SUBMIT = 'ON_TASK_SUBMIT';
export const ON_TASK_COMPLETE = 'ON_TASK_COMPLETE';
export const ON_TASK_UNCOMPLETE = 'ON_TASK_UNCOMPLETE';
export const TOGGLE_TASK_IMPORTANT = 'TOGGLE_TASK_IMPORTANT';
export const DELETE_TASK = 'DELETE_TASK';
