//ui actions
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const ACTIVE_ADD_TASK = "ACTIVE_ADD_TASK";
export const DEACTIVE_ADD_TASK = "DEACTIVE_ADD_TASK";
export const TOOGLE_COMPLETE_TASK_SHOW = "COMPLETE_TASK_SHOW";

//my day task action

export const ON_TASK_SUBMIT = "ON_TASK_SUBMIT";
export const ON_TASK_COMPLETE = "ON_TASK_COMPLETE";
export const ON_TASK_UNCOMPLETE = "ON_TASK_UNCOMPLETE";
